clc;
clear all;
A=1;
B=3;
Fs = 15000 + 100*A + 50*B;
figure;
[data1 Fs] = audioread('test1.wav');
data1_fft = fft(data1);
data1_fft = fftshift(data1_fft);
plot(abs(data1_fft(:,1)));
figure;
[data2 Fs] = audioread('test2.wav');
data2_fft = fft(data2);
data2_fft =fftshift(data2_fft);
plot(abs(data2_fft(:,1)));
figure;
[data3 Fs] = audioread('test3.wav');
data3_fft = fft(data3);
data3_fft =fftshift(data3_fft);
plot(abs(data3_fft(:,1)));
figure;
[data4 Fs] = audioread('test4.wav');
data4_fft = fft(data4);
data4_fft =fftshift(data4_fft);
plot(abs(data4_fft(:,1)));
figure;
[data5 Fs] = audioread('test5.wav');
data5_fft = fft(data5);
data5_fft =fftshift(data5_fft);
plot(abs(data5_fft(:,1)));
figure;
[data6 Fs] = audioread('test6.wav');
data6_fft = fft(data6);
data6_fft =fftshift(data6_fft);
plot(abs(data6_fft(:,1)));
